-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. ENUMS
create type article_status as enum (
  'Draft', 
  'Debate Duration voting opened', 
  'Debate ongoing', 
  'Voting opened', 
  'Approuved', 
  'Rejected', 
  'Ignored'
);

create type article_type as enum (
  'consitutional', 
  'law'
);

create type report_reason as enum (
  'Vulgar', 
  'Threat and intimidation', 
  'Out of scope', 
  'Sensible information leaked', 
  'Sexual abuse content'
);

create type debate_duration as enum (
  'One Month', 
  'Two Months', 
  'Three Months', 
  'Four Month', 
  'Five Month', 
  'Six Month'
);

create type vote_type as enum (
  'Voting_opened', 
  'Debate_Duration_voting'
);

-- 2. TABLES

-- Users (Profiles)
-- Note: This table extends Supabase's auth.users
create table public.users (
  id uuid references auth.users on delete cascade not null primary key,
  firstname text,
  lastname text,
  creationdate timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Articles
create table public.articles (
  id bigint generated by default as identity primary key,
  title text not null,
  goal text,
  content text,
  status article_status default 'Draft',
  type article_type not null,
  creationdate timestamp with time zone default timezone('utc'::text, now()) not null,
  statuschangedate timestamp with time zone,
  author_id uuid references public.users(id)
);

-- Debate Spaces
create table public.debatespaces (
  id bigint generated by default as identity primary key,
  article_id bigint references public.articles(id) on delete cascade unique not null,
  creationdate timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Topics
create table public.topics (
  id bigint generated by default as identity primary key,
  debatespace_id bigint references public.debatespaces(id) on delete cascade not null,
  title text not null,
  creationdate timestamp with time zone default timezone('utc'::text, now()) not null,
  lastupdate timestamp with time zone default timezone('utc'::text, now()) not null,
  author_id uuid references public.users(id)
);

-- Messages
create table public.messages (
  id bigint generated by default as identity primary key,
  topic_id bigint references public.topics(id) on delete cascade not null,
  author_id uuid references public.users(id),
  content text not null,
  creationdate timestamp with time zone default timezone('utc'::text, now()) not null,
  like_count int default 0,
  dislike_count int default 0
);

-- Message Reports
create table public.message_reported (
  id bigint generated by default as identity primary key,
  message_id bigint references public.messages(id) on delete cascade not null,
  reporter_id uuid references public.users(id),
  reason report_reason not null,
  reportdate timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Voting Opened Result
create table public.voting_opened_result (
  id bigint generated by default as identity primary key,
  article_id bigint references public.articles(id) on delete cascade unique not null,
  creationdate timestamp with time zone default timezone('utc'::text, now()) not null,
  nb_approve int default 0,
  nb_reject int default 0
);

-- Debate Duration Voting Result
create table public.debate_duration_voting_opened_result (
  id bigint generated by default as identity primary key,
  article_id bigint references public.articles(id) on delete cascade unique not null,
  voted_debate_duration debate_duration,
  votecount_one_month int default 0,
  votecount_two_months int default 0,
  votecount_three_months int default 0,
  votecount_four_months int default 0,
  votecount_five_months int default 0,
  votecount_six_months int default 0
);

-- Voting History
create table public.voting_history (
  id bigint generated by default as identity primary key,
  article_id bigint references public.articles(id) on delete cascade not null,
  voter_id uuid references public.users(id),
  typevote vote_type not null,
  votedate timestamp with time zone default timezone('utc'::text, now()) not null,
  votevalue text -- Encrypted client-side
);

-- 3. SECURITY (RLS)
-- Enable Row Level Security on all tables
alter table public.users enable row level security;
alter table public.articles enable row level security;
alter table public.debatespaces enable row level security;
alter table public.topics enable row level security;
alter table public.messages enable row level security;
alter table public.message_reported enable row level security;
alter table public.voting_opened_result enable row level security;
alter table public.debate_duration_voting_opened_result enable row level security;
alter table public.voting_history enable row level security;

-- Basic Policies (Open for now, can be tightened later)
create policy "Public profiles are viewable by everyone." on public.users for select using (true);
create policy "Users can insert their own profile." on public.users for insert with check (auth.uid() = id);

create policy "Articles are viewable by everyone." on public.articles for select using (true);
create policy "Authenticated users can create articles." on public.articles for insert with check (auth.role() = 'authenticated');

-- (Add more policies as needed for other tables)
